services:
  - type: web
    name: colorcube
    env: node
    plan: free
    rootDir: .
    packageManager: yarn
    buildCommand: yarn install && yarn build
    startCommand: yarn start
    envVars:
      - key: NODE_ENV
        value: production
