services:
  - type: web
    name: colorcube
    env: node
    plan: free
    buildCommand: yarn && yarn build
    startCommand: yarn start
    envVars:
      - key: NODE_ENV
        value: production
